export interface GalleryImage {
  id: string
  src: string
  alt: string
  width: number
  height: number
}

export interface Gallery {
  title: string
  images: GalleryImage[]
}

const GALLERIES: Record<string, Gallery> = {
  'sunday-service': {
    title: 'Sunday Service',
    images: [
      {
        id: 'ss1',
        src: 'https://picsum.photos/seed/ss1/400/600',
        alt: 'Congregation in worship',
        width: 400,
        height: 600,
      },
      {
        id: 'ss2',
        src: 'https://picsum.photos/seed/ss2/400/300',
        alt: 'Sunday morning gathering',
        width: 400,
        height: 300,
      },
      {
        id: 'ss3',
        src: 'https://picsum.photos/seed/ss3/400/400',
        alt: 'Bible reading during service',
        width: 400,
        height: 400,
      },
      {
        id: 'ss4',
        src: 'https://picsum.photos/seed/ss4/400/560',
        alt: 'Choir leading praise',
        width: 400,
        height: 560,
      },
      {
        id: 'ss5',
        src: 'https://picsum.photos/seed/ss5/400/300',
        alt: 'Communion being served',
        width: 400,
        height: 300,
      },
      {
        id: 'ss6',
        src: 'https://picsum.photos/seed/ss6/400/500',
        alt: 'Preacher at the pulpit',
        width: 400,
        height: 500,
      },
      {
        id: 'ss7',
        src: 'https://picsum.photos/seed/ss7/400/300',
        alt: 'Members fellowshipping',
        width: 400,
        height: 300,
      },
      {
        id: 'ss8',
        src: 'https://picsum.photos/seed/ss8/400/450',
        alt: 'Children in Sunday school',
        width: 400,
        height: 450,
      },
      {
        id: 'ss9',
        src: 'https://picsum.photos/seed/ss9/400/280',
        alt: 'Offering being collected',
        width: 400,
        height: 280,
      },
      {
        id: 'ss10',
        src: 'https://picsum.photos/seed/ss10/400/620',
        alt: 'Baptism ceremony',
        width: 400,
        height: 620,
      },
      {
        id: 'ss11',
        src: 'https://picsum.photos/seed/ss11/400/300',
        alt: 'Opening prayer',
        width: 400,
        height: 300,
      },
      {
        id: 'ss12',
        src: 'https://picsum.photos/seed/ss12/400/480',
        alt: 'Singing during worship',
        width: 400,
        height: 480,
      },
      {
        id: 'ss13',
        src: 'https://picsum.photos/seed/ss13/400/300',
        alt: 'Welcome announcement',
        width: 400,
        height: 300,
      },
      {
        id: 'ss14',
        src: 'https://picsum.photos/seed/ss14/400/540',
        alt: 'Elders leading the congregation',
        width: 400,
        height: 540,
      },
      {
        id: 'ss15',
        src: 'https://picsum.photos/seed/ss15/400/320',
        alt: 'Congregation exiting after service',
        width: 400,
        height: 320,
      },
      {
        id: 'ss16',
        src: 'https://picsum.photos/seed/ss16/400/600',
        alt: 'Youth in worship',
        width: 400,
        height: 600,
      },
      {
        id: 'ss17',
        src: 'https://picsum.photos/seed/ss17/400/340',
        alt: "Deacons serving the Lord's supper",
        width: 400,
        height: 340,
      },
      {
        id: 'ss18',
        src: 'https://picsum.photos/seed/ss18/400/460',
        alt: 'Sisters in worship',
        width: 400,
        height: 460,
      },
    ],
  },
  'gospel-meeting': {
    title: 'Gospel Meeting',
    images: [
      {
        id: 'gm1',
        src: 'https://picsum.photos/seed/gm1/400/560',
        alt: 'Guest speaker at gospel meeting',
        width: 400,
        height: 560,
      },
      {
        id: 'gm2',
        src: 'https://picsum.photos/seed/gm2/400/300',
        alt: 'Audience listening attentively',
        width: 400,
        height: 300,
      },
      {
        id: 'gm3',
        src: 'https://picsum.photos/seed/gm3/400/420',
        alt: 'Outdoor evening session',
        width: 400,
        height: 420,
      },
      {
        id: 'gm4',
        src: 'https://picsum.photos/seed/gm4/400/300',
        alt: 'Banner at the entrance',
        width: 400,
        height: 300,
      },
      {
        id: 'gm5',
        src: 'https://picsum.photos/seed/gm5/400/580',
        alt: 'Baptism after gospel meeting',
        width: 400,
        height: 580,
      },
      {
        id: 'gm6',
        src: 'https://picsum.photos/seed/gm6/400/300',
        alt: 'Members welcoming visitors',
        width: 400,
        height: 300,
      },
      {
        id: 'gm7',
        src: 'https://picsum.photos/seed/gm7/400/440',
        alt: 'Evening prayer session',
        width: 400,
        height: 440,
      },
      {
        id: 'gm8',
        src: 'https://picsum.photos/seed/gm8/400/300',
        alt: 'Song service',
        width: 400,
        height: 300,
      },
      {
        id: 'gm9',
        src: 'https://picsum.photos/seed/gm9/400/500',
        alt: 'Closing remarks',
        width: 400,
        height: 500,
      },
      {
        id: 'gm10',
        src: 'https://picsum.photos/seed/gm10/400/320',
        alt: 'Group fellowship after service',
        width: 400,
        height: 320,
      },
      {
        id: 'gm11',
        src: 'https://picsum.photos/seed/gm11/400/600',
        alt: 'Special choir performance',
        width: 400,
        height: 600,
      },
      {
        id: 'gm12',
        src: 'https://picsum.photos/seed/gm12/400/340',
        alt: 'Announcement board',
        width: 400,
        height: 340,
      },
      {
        id: 'gm13',
        src: 'https://picsum.photos/seed/gm13/400/480',
        alt: 'Minister greeting guests',
        width: 400,
        height: 480,
      },
      {
        id: 'gm14',
        src: 'https://picsum.photos/seed/gm14/400/300',
        alt: 'Crowd at the auditorium',
        width: 400,
        height: 300,
      },
      {
        id: 'gm15',
        src: 'https://picsum.photos/seed/gm15/400/520',
        alt: 'Preacher expounding the word',
        width: 400,
        height: 520,
      },
    ],
  },
  'bible-class': {
    title: 'Bible Class',
    images: [
      {
        id: 'bc1',
        src: 'https://picsum.photos/seed/bc1/400/500',
        alt: 'Bible class teacher at board',
        width: 400,
        height: 500,
      },
      {
        id: 'bc2',
        src: 'https://picsum.photos/seed/bc2/400/300',
        alt: 'Students reading scripture',
        width: 400,
        height: 300,
      },
      {
        id: 'bc3',
        src: 'https://picsum.photos/seed/bc3/400/450',
        alt: 'Group discussion',
        width: 400,
        height: 450,
      },
      {
        id: 'bc4',
        src: 'https://picsum.photos/seed/bc4/400/320',
        alt: 'Youth bible class',
        width: 400,
        height: 320,
      },
      {
        id: 'bc5',
        src: 'https://picsum.photos/seed/bc5/400/580',
        alt: 'Sunday school lesson',
        width: 400,
        height: 580,
      },
      {
        id: 'bc6',
        src: 'https://picsum.photos/seed/bc6/400/300',
        alt: 'Open bible on table',
        width: 400,
        height: 300,
      },
      {
        id: 'bc7',
        src: 'https://picsum.photos/seed/bc7/400/420',
        alt: 'Children class',
        width: 400,
        height: 420,
      },
      {
        id: 'bc8',
        src: 'https://picsum.photos/seed/bc8/400/300',
        alt: 'Note taking during class',
        width: 400,
        height: 300,
      },
      {
        id: 'bc9',
        src: 'https://picsum.photos/seed/bc9/400/540',
        alt: 'Question and answer session',
        width: 400,
        height: 540,
      },
      {
        id: 'bc10',
        src: 'https://picsum.photos/seed/bc10/400/300',
        alt: 'Memory verse recitation',
        width: 400,
        height: 300,
      },
      {
        id: 'bc11',
        src: 'https://picsum.photos/seed/bc11/400/460',
        alt: 'Women bible study group',
        width: 400,
        height: 460,
      },
      {
        id: 'bc12',
        src: 'https://picsum.photos/seed/bc12/400/340',
        alt: 'Devotional time',
        width: 400,
        height: 340,
      },
      {
        id: 'bc13',
        src: 'https://picsum.photos/seed/bc13/400/600',
        alt: "Men's class on Wednesday",
        width: 400,
        height: 600,
      },
      {
        id: 'bc14',
        src: 'https://picsum.photos/seed/bc14/400/300',
        alt: 'Class closing prayer',
        width: 400,
        height: 300,
      },
      {
        id: 'bc15',
        src: 'https://picsum.photos/seed/bc15/400/480',
        alt: 'Lesson material distribution',
        width: 400,
        height: 480,
      },
      {
        id: 'bc16',
        src: 'https://picsum.photos/seed/bc16/400/320',
        alt: 'Parents and children together',
        width: 400,
        height: 320,
      },
    ],
  },
  evangelism: {
    title: 'Evangelism',
    images: [
      {
        id: 'ev1',
        src: 'https://picsum.photos/seed/ev1/400/540',
        alt: 'Door-to-door evangelism team',
        width: 400,
        height: 540,
      },
      {
        id: 'ev2',
        src: 'https://picsum.photos/seed/ev2/400/300',
        alt: 'Tract distribution in market',
        width: 400,
        height: 300,
      },
      {
        id: 'ev3',
        src: 'https://picsum.photos/seed/ev3/400/460',
        alt: 'Street preaching',
        width: 400,
        height: 460,
      },
      {
        id: 'ev4',
        src: 'https://picsum.photos/seed/ev4/400/300',
        alt: 'Personal Bible study session',
        width: 400,
        height: 300,
      },
      {
        id: 'ev5',
        src: 'https://picsum.photos/seed/ev5/400/600',
        alt: 'Baptism after study',
        width: 400,
        height: 600,
      },
      {
        id: 'ev6',
        src: 'https://picsum.photos/seed/ev6/400/320',
        alt: 'Evangelism planning meeting',
        width: 400,
        height: 320,
      },
      {
        id: 'ev7',
        src: 'https://picsum.photos/seed/ev7/400/480',
        alt: 'Outreach at university campus',
        width: 400,
        height: 480,
      },
      {
        id: 'ev8',
        src: 'https://picsum.photos/seed/ev8/400/300',
        alt: 'Sharing the gospel',
        width: 400,
        height: 300,
      },
      {
        id: 'ev9',
        src: 'https://picsum.photos/seed/ev9/400/520',
        alt: 'New convert study',
        width: 400,
        height: 520,
      },
      {
        id: 'ev10',
        src: 'https://picsum.photos/seed/ev10/400/300',
        alt: 'Evangelism team group',
        width: 400,
        height: 300,
      },
      {
        id: 'ev11',
        src: 'https://picsum.photos/seed/ev11/400/580',
        alt: 'Hospital outreach visit',
        width: 400,
        height: 580,
      },
      {
        id: 'ev12',
        src: 'https://picsum.photos/seed/ev12/400/340',
        alt: 'Village evangelism',
        width: 400,
        height: 340,
      },
      {
        id: 'ev13',
        src: 'https://picsum.photos/seed/ev13/400/440',
        alt: 'Prison ministry',
        width: 400,
        height: 440,
      },
      {
        id: 'ev14',
        src: 'https://picsum.photos/seed/ev14/400/300',
        alt: 'Follow-up visit to new member',
        width: 400,
        height: 300,
      },
      {
        id: 'ev15',
        src: 'https://picsum.photos/seed/ev15/400/560',
        alt: 'Youth evangelism day',
        width: 400,
        height: 560,
      },
    ],
  },
}

export function useGalleryData(slug: string) {
  const gallery = GALLERIES[slug] ?? null
  return { gallery, galleries: GALLERIES }
}
