import type {
  PublicSermon,
  Lesson,
  RecordedStream,
  LiveStream,
  ChurchEvent,
  Congregation,
} from '~/types/public'

const SERMONS: PublicSermon[] = [
  {
    id: '1',
    slug: 'the-foundation-of-faith',
    title: 'The Foundation of Faith',
    preacher: 'Bro. Emmanuel Okon',
    date: 'April 6, 2025',
    tags: ['Faith', 'Foundation'],
    thumbnailSrc: 'https://picsum.photos/seed/sermon1/800/450',
    videoSrc: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    description:
      'An in-depth study on what genuine biblical faith looks like and how it sustains the believer through every trial.',
    lessonPoints: [
      'Faith is the assurance of things hoped for (Hebrews 11:1)',
      'Without faith it is impossible to please God (Hebrews 11:6)',
      'Faith comes by hearing the word of God (Romans 10:17)',
      "True faith produces obedience to God's commands",
      'Faith must be accompanied by works (James 2:17)',
    ],
    soulWinnerPoints: [
      'Share the gospel boldly with your neighbors',
      'Invite friends and family to worship services',
      'Be a living example of faith in daily life',
      'Study the Bible with those who are seeking truth',
    ],
    relatedIds: ['2', '3', '6'],
  },
  {
    id: '2',
    slug: 'grace-abounding-to-sinners',
    title: 'Grace Abounding to the Chief of Sinners',
    preacher: 'Bro. Michael Essien',
    date: 'March 30, 2025',
    tags: ['Grace', 'Salvation'],
    thumbnailSrc: 'https://picsum.photos/seed/sermon2/800/450',
    videoSrc: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    description:
      "An exposition of God's boundless grace toward all who come to Him in humble repentance and obedient faith.",
    lessonPoints: [
      "Grace is God's unmerited favour given to those who obey",
      'Paul described himself as chief of sinners yet found mercy',
      'Grace does not make void the law but fulfils it in Christ',
      'We are saved by grace through faith — not of works (Eph 2:8)',
      'Grace teaches us to live soberly and righteously (Titus 2:12)',
    ],
    soulWinnerPoints: [
      "Tell your story of how God's grace transformed your life",
      'Point the lost to the grace available in Christ Jesus',
      'Be patient with those still wrestling with sin',
      'Lead by example — let grace be evident in your conduct',
    ],
    relatedIds: ['1', '6', '10'],
  },
  {
    id: '3',
    slug: 'the-way-truth-and-life',
    title: 'The Way, The Truth, and The Life',
    preacher: 'Bro. David Akpan',
    date: 'March 23, 2025',
    tags: ['Truth', 'Gospel'],
    thumbnailSrc: 'https://picsum.photos/seed/sermon3/800/450',
    videoSrc: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    description:
      'A thorough examination of John 14:6 and the exclusive claim of Jesus Christ as the only path to eternal life.',
    lessonPoints: [
      'Jesus is the only way to the Father (John 14:6)',
      "The truth of God's word is settled forever (Psalm 119:89)",
      'Eternal life is found only in Christ (1 John 5:11-12)',
      'No other name under heaven given for salvation (Acts 4:12)',
      'Walking in the truth is walking in the light of God',
    ],
    soulWinnerPoints: [
      'Confidently declare Jesus as the only Saviour',
      'Use scripture to point others to the truth',
      'Do not compromise the gospel for the sake of popularity',
      'Let your walk match your proclamation of truth',
    ],
    relatedIds: ['1', '2', '7'],
  },
  {
    id: '4',
    slug: 'walking-in-the-spirit',
    title: 'Walking in the Spirit',
    preacher: 'Bro. John Udoh',
    date: 'March 16, 2025',
    tags: ['Faith', 'Scripture'],
    thumbnailSrc: 'https://picsum.photos/seed/sermon4/800/450',
    videoSrc: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    description:
      'Exploring what it practically means for the New Testament Christian to walk by the Spirit in everyday life.',
    lessonPoints: [
      'Walk in the Spirit and you will not fulfil the lust of the flesh (Gal 5:16)',
      'The fruit of the Spirit is the evidence of a Spirit-led life',
      "Being led by the Spirit means being guided by God's word",
      'Quenching the Spirit comes through disobedience and neglect',
      'A Spirit-filled church is a worshipping, serving church',
    ],
    soulWinnerPoints: [
      'Let the fruit of the Spirit attract others to Christ in you',
      'Pray for the courage to speak about your faith',
      'Demonstrate the love of God to your community',
      'Mentor younger believers to walk in the Spirit daily',
    ],
    relatedIds: ['1', '5', '8'],
  },
  {
    id: '5',
    slug: 'the-great-commission',
    title: 'The Great Commission',
    preacher: 'Bro. Philip Okafor',
    date: 'March 9, 2025',
    tags: ['Gospel', 'Church'],
    thumbnailSrc: 'https://picsum.photos/seed/sermon5/800/450',
    videoSrc: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    description:
      'Understanding the mandate given by Christ to every believer to go into all the world and preach the gospel.',
    lessonPoints: [
      'Go therefore and make disciples of all nations (Matt 28:19)',
      'Every Christian is a commissioned ambassador for Christ',
      'The gospel must be preached to every creature (Mark 16:15)',
      "The church's mission is both local and global in scope",
      'We preach not ourselves but Christ Jesus the Lord',
    ],
    soulWinnerPoints: [
      'Begin with your immediate household and neighbourhood',
      'Use every opportunity to share the good news of Christ',
      'Support missionaries and evangelism efforts financially',
      'Train and equip others to fulfil the great commission',
    ],
    relatedIds: ['3', '6', '9'],
  },
  {
    id: '6',
    slug: 'repentance-and-baptism',
    title: "Repentance and Baptism: God's Commands",
    preacher: 'Bro. Samuel Etim',
    date: 'March 2, 2025',
    tags: ['Baptism', 'Salvation'],
    thumbnailSrc: 'https://picsum.photos/seed/sermon6/800/450',
    videoSrc: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    description:
      'A scriptural exploration of repentance and baptism as essential, non-negotiable acts of obedience for salvation.',
    lessonPoints: [
      'Repent and be baptized for the remission of sins (Acts 2:38)',
      'Baptism is a burial — dying to sin and rising in Christ (Rom 6:4)',
      'Repentance is a godly sorrow that leads to genuine change',
      'Baptism is a covenant act between the believer and God',
      'There is only one baptism — immersion in water (Eph 4:5)',
    ],
    soulWinnerPoints: [
      'Call people to genuine repentance, not just surface change',
      'Teach the scriptural design and purpose of baptism',
      'Be ready to baptize those who obey the gospel promptly',
      'Follow up with new converts to encourage their growth',
    ],
    relatedIds: ['2', '10', '1'],
  },
  {
    id: '7',
    slug: 'the-power-of-prayer',
    title: 'The Power of Prayer',
    preacher: 'Bro. James Nwachukwu',
    date: 'February 23, 2025',
    tags: ['Faith', 'Scripture'],
    thumbnailSrc: 'https://picsum.photos/seed/sermon7/800/450',
    videoSrc: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    description:
      'Discovering the transformative power of prayer in the life of the church and the individual believer.',
    lessonPoints: [
      'The effective, fervent prayer of a righteous man avails much (Jas 5:16)',
      'Jesus taught His disciples to pray with faith and persistence',
      'Prayer is communion with God — it shapes our heart to His will',
      'The early church devoted itself to prayer (Acts 2:42)',
      'Praying without ceasing is a mark of the Spirit-filled Christian',
    ],
    soulWinnerPoints: [
      'Pray for the lost by name in your daily devotions',
      'Intercede for open doors to share the gospel',
      'Teach new converts the discipline of daily prayer',
      'Organise prayer walks in your community',
    ],
    relatedIds: ['4', '8', '11'],
  },
  {
    id: '8',
    slug: 'faith-without-works-is-dead',
    title: 'Faith Without Works Is Dead',
    preacher: 'Bro. Peter Eze',
    date: 'February 16, 2025',
    tags: ['Faith', 'Gospel'],
    thumbnailSrc: 'https://picsum.photos/seed/sermon8/800/450',
    videoSrc: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    description:
      'A study of James chapter 2 showing that genuine faith is always expressed through visible, obedient action.',
    lessonPoints: [
      'Faith that does not produce works is dead (James 2:17)',
      'Abraham was justified by works when he offered Isaac (James 2:21)',
      "Rahab's faith was demonstrated by her actions toward the spies",
      'Good works are the natural fruit of genuine saving faith',
      'We do not earn salvation by works, but works are its evidence',
    ],
    soulWinnerPoints: [
      'Let your good works before men glorify your Father (Matt 5:16)',
      'Serve your community practically in the name of Christ',
      'Demonstrate care for orphans, widows, and the poor',
      'Your consistent righteous life is a powerful witness',
    ],
    relatedIds: ['1', '4', '7'],
  },
  {
    id: '9',
    slug: 'church-of-christ-in-new-testament',
    title: 'The Church of Christ in the New Testament',
    preacher: 'Bro. Emmanuel Okon',
    date: 'February 9, 2025',
    tags: ['Church', 'Foundation'],
    thumbnailSrc: 'https://picsum.photos/seed/sermon9/800/450',
    videoSrc: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    description:
      'An overview of the identity, design, worship, and mission of the New Testament church established by Christ.',
    lessonPoints: [
      'Christ is the head of the church (Eph 1:22-23)',
      'The church was established on the day of Pentecost (Acts 2)',
      'Members of the church are those baptized into Christ (Gal 3:27)',
      "New Testament worship: singing, prayer, Lord's supper, giving, teaching",
      'Each congregation is autonomous and led by elders (Acts 14:23)',
    ],
    soulWinnerPoints: [
      'Help people understand the difference between the church and denominations',
      'Invite others to see what the New Testament church looks like',
      'Be proud of belonging to the church Christ promised to build',
      "Live as a worthy representative of the Lord's body",
    ],
    relatedIds: ['5', '6', '10'],
  },
  {
    id: '10',
    slug: 'salvation-gods-plan-for-man',
    title: "Salvation: God's Plan for Man",
    preacher: 'Bro. Michael Essien',
    date: 'February 2, 2025',
    tags: ['Salvation', 'Gospel'],
    thumbnailSrc: 'https://picsum.photos/seed/sermon10/800/450',
    videoSrc: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    description:
      "A complete presentation of God's plan of salvation from hearing the gospel to faithful Christian living.",
    lessonPoints: [
      "Hear the gospel — faith comes by hearing God's word (Rom 10:17)",
      'Believe — without faith it is impossible to please God (Heb 11:6)',
      'Repent of sins — godly sorrow leads to salvation (2 Cor 7:10)',
      'Confess Christ — with the mouth confession is made (Rom 10:10)',
      'Be baptized — for the remission of sins (Acts 2:38)',
      'Live faithfully — be faithful unto death (Rev 2:10)',
    ],
    soulWinnerPoints: [
      "Walk unbelievers through God's plan step by step",
      'Use Acts 2 as your primary text for the plan of salvation',
      'Never rush the process — ensure genuine understanding',
      'Celebrate and support every soul who obeys the gospel',
    ],
    relatedIds: ['6', '2', '9'],
  },
  {
    id: '11',
    slug: 'the-blood-of-the-covenant',
    title: 'The Blood of the Covenant',
    preacher: 'Bro. David Akpan',
    date: 'January 26, 2025',
    tags: ['Gospel', 'Church'],
    thumbnailSrc: 'https://picsum.photos/seed/sermon11/800/450',
    videoSrc: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    description:
      'A meditation on the power and significance of the blood of Jesus Christ as the basis of our new covenant with God.',
    lessonPoints: [
      'Without the shedding of blood there is no remission (Heb 9:22)',
      'The blood of Christ cleanses us from all sin (1 John 1:7)',
      "The Lord's supper commemorates the new covenant in His blood",
      'We overcome by the blood of the Lamb and our testimony (Rev 12:11)',
      'The blood speaks better things than the blood of Abel (Heb 12:24)',
    ],
    soulWinnerPoints: [
      'Point the lost to the cleansing power of the blood of Christ',
      "Explain the significance of the Lord's supper to new converts",
      "Help others understand why Christ's sacrifice is sufficient",
      'Let the power of redemption motivate your witness',
    ],
    relatedIds: ['2', '6', '10'],
  },
  {
    id: '12',
    slug: 'bearing-good-fruit',
    title: 'Bearing Good Fruit for the Kingdom',
    preacher: 'Bro. John Udoh',
    date: 'January 19, 2025',
    tags: ['Faith', 'Church'],
    thumbnailSrc: 'https://picsum.photos/seed/sermon12/800/450',
    videoSrc: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    description:
      'Examining what it means to abide in the vine and bear abundant, lasting fruit for the glory of God.',
    lessonPoints: [
      'I am the vine, you are the branches — abide in Me (John 15:5)',
      'Every branch that does not bear fruit is taken away (John 15:2)',
      'The fruit of righteousness is sown in peace by peacemakers (Jas 3:18)',
      'We were created in Christ Jesus for good works (Eph 2:10)',
      'A good tree cannot produce bad fruit (Matthew 7:18)',
    ],
    soulWinnerPoints: [
      'Your transformed life is the most compelling argument for Christ',
      'Invest in younger believers — reproduce yourself in others',
      'Seek opportunities to plant new congregations in unreached areas',
      'Be consistent — lasting fruit grows from consistent discipleship',
    ],
    relatedIds: ['8', '4', '1'],
  },
]

const LESSONS: Lesson[] = [
  {
    id: 'l1',
    slug: 'attendance-and-faithfulness',
    title: 'Attendance and Faithfulness to God',
    preacher: 'Bro. Emmanuel Okon',
    date: 'April 6, 2025',
    tags: ['Attendance'],
    thumbnailSrc: 'https://picsum.photos/seed/lesson1/800/450',
    overviewGoals: [
      'Understand why regular attendance is a spiritual discipline',
      'Identify the consequences of forsaking the assembly',
      'Develop a personal commitment to consistent worship',
      'Encourage fellow members in faithful attendance',
    ],
    churchDuties: [
      'Elders must regularly check on absent members with pastoral care',
      'Deacons should coordinate weekly attendance records',
      "Every member is their brother's keeper — check on the absent",
      'The congregation should create a culture of accountability',
    ],
    scripture:
      '"Not forsaking the assembling of ourselves together, as the manner of some is; but exhorting one another: and so much the more, as ye see the day approaching." — Hebrews 10:25',
    relatedIds: ['l2', 'l8', 'l9'],
  },
  {
    id: 'l2',
    slug: 'court-of-the-congregation',
    title: 'The Court of the Congregation',
    preacher: 'Bro. Michael Essien',
    date: 'March 30, 2025',
    tags: ['Court'],
    thumbnailSrc: 'https://picsum.photos/seed/lesson2/800/450',
    overviewGoals: [
      'Understand the biblical basis for church discipline',
      'Learn the proper process for addressing sin in the church',
      'See how church courts maintain the purity of the body',
      'Appreciate restoration as the ultimate goal of discipline',
    ],
    churchDuties: [
      'Elders bear primary responsibility for maintaining doctrinal purity',
      'Matters must be handled with prayer, love, and sobriety',
      'Two or three witnesses are required before any formal action',
      'The goal is always restoration, not punishment',
    ],
    scripture:
      '"Moreover if thy brother shall trespass against thee, go and tell him his fault between thee and him alone: if he shall hear thee, thou hast gained thy brother." — Matthew 18:15',
    relatedIds: ['l1', 'l4', 'l10'],
  },
  {
    id: 'l3',
    slug: 'truth-that-sets-free',
    title: 'The Truth That Sets Free',
    preacher: 'Bro. David Akpan',
    date: 'March 23, 2025',
    tags: ['Truth'],
    thumbnailSrc: 'https://picsum.photos/seed/lesson3/800/450',
    overviewGoals: [
      "Define truth as it is presented in God's word",
      'Understand how truth liberates the soul from bondage',
      'Identify false teachings that enslave rather than free',
      "Commit to a lifetime of walking in God's truth",
    ],
    churchDuties: [
      "Teachers must preach only the truth of God's word, nothing more",
      'Members must test all teaching against the scripture',
      'Elders must guard against false teachers in the flock',
      'The church must remain a pillar and ground of the truth',
    ],
    scripture: '"And ye shall know the truth, and the truth shall make you free." — John 8:32',
    relatedIds: ['l1', 'l5', 'l7'],
  },
  {
    id: 'l4',
    slug: 'winning-back-the-backslider',
    title: 'Winning Back the Backslider',
    preacher: 'Bro. John Udoh',
    date: 'March 16, 2025',
    tags: ['Backsliders'],
    thumbnailSrc: 'https://picsum.photos/seed/lesson4/800/450',
    overviewGoals: [
      'Understand why members fall away from the faith',
      'Learn compassionate strategies for restoring the fallen',
      'Develop a congregational culture of watching over one another',
      'Study the parable of the lost sheep and its application',
    ],
    churchDuties: [
      'Every member should pray regularly for those who have fallen away',
      'Elders must make personal visits to wayward members',
      'Deacons should maintain up-to-date records of absent members',
      'Youth leaders must give special attention to young backsliders',
    ],
    scripture:
      '"Brethren, if a man be overtaken in a fault, ye which are spiritual, restore such an one in the spirit of meekness; considering thyself, lest thou also be tempted." — Galatians 6:1',
    relatedIds: ['l1', 'l2', 'l8'],
  },
  {
    id: 'l5',
    slug: 'baptism-in-the-new-testament',
    title: 'Baptism in the New Testament',
    preacher: 'Bro. Philip Okafor',
    date: 'March 9, 2025',
    tags: ['Baptist'],
    thumbnailSrc: 'https://picsum.photos/seed/lesson5/800/450',
    overviewGoals: [
      'Establish the New Testament design of baptism by immersion',
      'Understand the purpose of baptism in the plan of salvation',
      'Refute the false doctrines surrounding baptism',
      'Encourage unbaptised seekers to obey the gospel today',
    ],
    churchDuties: [
      'Preachers must teach baptism as God ordained it in scripture',
      'The congregation must celebrate every new baptism joyfully',
      'Members should be able to explain why we baptize by immersion',
      'Elders must ensure proper follow-up with all new converts',
    ],
    scripture:
      '"He that believeth and is baptized shall be saved; but he that believeth not shall be damned." — Mark 16:16',
    relatedIds: ['l3', 'l6', 'l9'],
  },
  {
    id: 'l6',
    slug: 'the-mission-of-the-church',
    title: 'The Mission of the Church',
    preacher: 'Bro. Samuel Etim',
    date: 'March 2, 2025',
    tags: ['Mission'],
    thumbnailSrc: 'https://picsum.photos/seed/lesson6/800/450',
    overviewGoals: [
      'Define the primary mission Christ gave to His church',
      'Understand benevolence, edification, and evangelism as pillars',
      'Evaluate how well our local congregation fulfils its mission',
      'Identify practical ways to advance the mission in our context',
    ],
    churchDuties: [
      'The treasury must support mission work and global evangelism',
      'Every congregation should have an active evangelism programme',
      'Members must be trained and equipped to share the gospel',
      'Elders must cast a vision for the mission before the congregation',
    ],
    scripture: '"Go ye into all the world, and preach the gospel to every creature." — Mark 16:15',
    relatedIds: ['l5', 'l7', 'l9'],
  },
  {
    id: 'l7',
    slug: 'developing-talents-for-god',
    title: 'Developing Your Talents for God',
    preacher: 'Bro. James Nwachukwu',
    date: 'February 23, 2025',
    tags: ['Talent'],
    thumbnailSrc: 'https://picsum.photos/seed/lesson7/800/450',
    overviewGoals: [
      'Identify the talents God has placed within you',
      'Understand the parable of the talents and its warning',
      'Commit to developing and deploying your gifts for God',
      'Appreciate how every talent serves the body of Christ',
    ],
    churchDuties: [
      'Leaders must identify and develop gifted members intentionally',
      'The congregation should create platforms for members to serve',
      'No talent is too small — all gifts honour God when used faithfully',
      'Mentorship must be built into the culture of the church',
    ],
    scripture:
      '"For unto every one that hath shall be given, and he shall have abundance: but from him that hath not shall be taken away even that which he hath." — Matthew 25:29',
    relatedIds: ['l6', 'l8', 'l12'],
  },
  {
    id: 'l8',
    slug: 'faith-and-practice',
    title: 'Faith and Practice in Daily Life',
    preacher: 'Bro. Peter Eze',
    date: 'February 16, 2025',
    tags: ['Sermons'],
    thumbnailSrc: 'https://picsum.photos/seed/lesson8/800/450',
    overviewGoals: [
      'Bridge the gap between Sunday worship and daily Christian living',
      'Understand that practice validates profession of faith',
      'Develop consistent habits of prayer, study, and service',
      'Hold each other accountable in daily spiritual disciplines',
    ],
    churchDuties: [
      'Preachers should address practical, everyday Christian challenges',
      'Bible class must be applied — not merely academic knowledge',
      'Home visits allow elders to assess the daily faith of members',
      'The whole church benefits when members practice what they preach',
    ],
    scripture:
      '"But be ye doers of the word, and not hearers only, deceiving your own selves." — James 1:22',
    relatedIds: ['l1', 'l3', 'l7'],
  },
  {
    id: 'l9',
    slug: 'evangelism-and-soul-winning',
    title: 'Evangelism and Soul Winning',
    preacher: 'Bro. Emmanuel Okon',
    date: 'February 9, 2025',
    tags: ['Mission'],
    thumbnailSrc: 'https://picsum.photos/seed/lesson9/800/450',
    overviewGoals: [
      'Understand the urgency of winning souls for Christ',
      'Learn simple, effective methods of personal evangelism',
      'Overcome fear and excuses that hinder us from witnessing',
      'Develop a personal soul-winning plan for the year',
    ],
    churchDuties: [
      'Every congregation should track baptisms and new converts yearly',
      'Evangelism training must be an annual programme for members',
      'Preachers should model personal evangelism for the congregation',
      'Budgets should reflect the priority of outreach and mission',
    ],
    scripture: '"He that winneth souls is wise." — Proverbs 11:30',
    relatedIds: ['l5', 'l6', 'l12'],
  },
  {
    id: 'l10',
    slug: 'role-of-elders-and-deacons',
    title: 'The Role of Elders and Deacons',
    preacher: 'Bro. Michael Essien',
    date: 'February 2, 2025',
    tags: ['Others'],
    thumbnailSrc: 'https://picsum.photos/seed/lesson10/800/450',
    overviewGoals: [
      'Study the qualifications of elders and deacons (1 Tim 3)',
      'Understand the distinct roles of shepherds and servants',
      'Appreciate the importance of recognising qualified leaders',
      'Encourage men in the congregation to aspire to service',
    ],
    churchDuties: [
      'Congregations must appoint elders who meet scriptural qualifications',
      'Deacons must be tested first before appointment (1 Tim 3:10)',
      'The two offices must work together for the health of the body',
      'Members must respect and submit to appointed leaders (Heb 13:17)',
    ],
    scripture:
      '"This is a true saying, if a man desire the office of a bishop, he desireth a good work." — 1 Timothy 3:1',
    relatedIds: ['l2', 'l6', 'l11'],
  },
  {
    id: 'l11',
    slug: 'christian-living-secular-world',
    title: 'Christian Living in a Secular World',
    preacher: 'Bro. David Akpan',
    date: 'January 26, 2025',
    tags: ['Others'],
    thumbnailSrc: 'https://picsum.photos/seed/lesson11/800/450',
    overviewGoals: [
      'Define what it means to be in the world but not of it',
      'Identify the pressures that secular culture places on believers',
      'Develop strategies for maintaining holiness in a fallen world',
      'Understand how to be salt and light in society',
    ],
    churchDuties: [
      'Youth ministry must address the specific pressures facing young people',
      'Preachers must speak to modern challenges with scriptural wisdom',
      'Elders should counsel members facing workplace and social pressures',
      'The church must not be conformed to the world (Rom 12:2)',
    ],
    scripture:
      '"And be not conformed to this world: but be ye transformed by the renewing of your mind." — Romans 12:2',
    relatedIds: ['l8', 'l3', 'l12'],
  },
  {
    id: 'l12',
    slug: 'prayer-and-fasting',
    title: 'Prayer and Fasting in the Church',
    preacher: 'Bro. John Udoh',
    date: 'January 19, 2025',
    tags: ['Others'],
    thumbnailSrc: 'https://picsum.photos/seed/lesson12/800/450',
    overviewGoals: [
      'Understand the purpose and power of fasting in Scripture',
      'Learn the proper attitude and practice of fasting',
      'Study the connection between prayer and fasting in the early church',
      'Develop a personal and congregational prayer and fasting culture',
    ],
    churchDuties: [
      'Leaders should call the congregation to corporate fasting at key moments',
      'Prayer meetings should be a fixture of congregational life',
      'New members should be taught the discipline of personal prayer',
      'The church should intercede together for the sick and the lost',
    ],
    scripture: '"Howbeit this kind goeth not out but by prayer and fasting." — Matthew 17:21',
    relatedIds: ['l7', 'l8', 'l9'],
  },
]

const RECORDED_STREAMS: RecordedStream[] = [
  {
    id: 'rs1',
    slug: 'sunday-worship-bread-of-life',
    title: 'Sunday Worship — The Bread of Life',
    serviceType: 'Sunday Worship',
    preacher: 'Bro. Emmanuel Okon',
    date: 'April 6, 2025',
    duration: '01:45:00',
    views: 1284,
    thumbnailSrc: 'https://picsum.photos/seed/stream1/800/450',
  },
  {
    id: 'rs2',
    slug: 'bible-class-epistles',
    title: 'Bible Class — Understanding the Epistles',
    serviceType: 'Bible Class',
    preacher: 'Bro. Michael Essien',
    date: 'April 3, 2025',
    duration: '01:20:00',
    views: 973,
    thumbnailSrc: 'https://picsum.photos/seed/stream2/800/450',
  },
  {
    id: 'rs3',
    slug: 'sunday-worship-good-shepherd',
    title: 'Sunday Worship — Jesus the Good Shepherd',
    serviceType: 'Sunday Worship',
    preacher: 'Bro. David Akpan',
    date: 'March 30, 2025',
    duration: '01:50:00',
    views: 2145,
    thumbnailSrc: 'https://picsum.photos/seed/stream3/800/450',
  },
  {
    id: 'rs4',
    slug: 'evangelism-service-going-out',
    title: 'Evangelism Service — Going Into All the World',
    serviceType: 'Evangelism',
    preacher: 'Bro. Philip Okafor',
    date: 'March 28, 2025',
    duration: '01:15:00',
    views: 648,
    thumbnailSrc: 'https://picsum.photos/seed/stream4/800/450',
  },
  {
    id: 'rs5',
    slug: 'sunday-school-psalms',
    title: 'Sunday School — Lessons from the Psalms',
    serviceType: 'Sunday School',
    preacher: 'Bro. Samuel Etim',
    date: 'March 23, 2025',
    duration: '01:30:00',
    views: 891,
    thumbnailSrc: 'https://picsum.photos/seed/stream5/800/450',
  },
  {
    id: 'rs6',
    slug: 'sunday-worship-armor-of-god',
    title: 'Sunday Worship — The Armor of God',
    serviceType: 'Sunday Worship',
    preacher: 'Bro. James Nwachukwu',
    date: 'March 16, 2025',
    duration: '01:40:00',
    views: 1567,
    thumbnailSrc: 'https://picsum.photos/seed/stream6/800/450',
  },
  {
    id: 'rs7',
    slug: 'bible-class-romans',
    title: 'Bible Class — The Book of Romans',
    serviceType: 'Bible Class',
    preacher: 'Bro. Peter Eze',
    date: 'March 13, 2025',
    duration: '02:00:00',
    views: 1102,
    thumbnailSrc: 'https://picsum.photos/seed/stream7/800/450',
  },
  {
    id: 'rs8',
    slug: 'sunday-worship-walking-by-faith',
    title: 'Sunday Worship — Walking by Faith',
    serviceType: 'Sunday Worship',
    preacher: 'Bro. Emmanuel Okon',
    date: 'March 9, 2025',
    duration: '01:35:00',
    views: 1834,
    thumbnailSrc: 'https://picsum.photos/seed/stream8/800/450',
  },
  {
    id: 'rs9',
    slug: 'sunday-school-gods-plan',
    title: "Sunday School — God's Plan for Man",
    serviceType: 'Sunday School',
    preacher: 'Bro. Michael Essien',
    date: 'March 2, 2025',
    duration: '01:25:00',
    views: 756,
    thumbnailSrc: 'https://picsum.photos/seed/stream9/800/450',
  },
  {
    id: 'rs10',
    slug: 'sunday-worship-lords-supper',
    title: "Sunday Worship — The Lord's Supper",
    serviceType: 'Sunday Worship',
    preacher: 'Bro. David Akpan',
    date: 'February 23, 2025',
    duration: '01:45:00',
    views: 2389,
    thumbnailSrc: 'https://picsum.photos/seed/stream10/800/450',
  },
  {
    id: 'rs11',
    slug: 'bible-class-prayer',
    title: 'Bible Class — Prayer in the New Testament',
    serviceType: 'Bible Class',
    preacher: 'Bro. John Udoh',
    date: 'February 20, 2025',
    duration: '01:10:00',
    views: 612,
    thumbnailSrc: 'https://picsum.photos/seed/stream11/800/450',
  },
  {
    id: 'rs12',
    slug: 'sunday-worship-resurrection',
    title: 'Sunday Worship — The Resurrection',
    serviceType: 'Sunday Worship',
    preacher: 'Bro. Philip Okafor',
    date: 'February 16, 2025',
    duration: '01:55:00',
    views: 3012,
    thumbnailSrc: 'https://picsum.photos/seed/stream12/800/450',
  },
]

const CURRENT_LIVE_STREAM: LiveStream = {
  id: 'live1',
  title: 'Sunday Worship Service — Abide in the Vine',
  congregation: 'Church of Christ, Ekot Ekpene',
  city: 'Ekot Ekpene',
  viewerCount: 3248,
  thumbnailSrc: 'https://picsum.photos/seed/live1/1200/600',
  startedAt: new Date().toISOString(),
}

const EVENTS: ChurchEvent[] = [
  {
    id: 'ev1',
    title: 'Annual Youth Convention 2025',
    day: '18',
    month: 'APR',
    location: 'Church Auditorium, Ekot Ekpene',
    time: '9:00 AM – 5:00 PM',
    colorClass: 'bg-blue-500',
  },
  {
    id: 'ev2',
    title: 'Monthly Bible Study Weekend',
    day: '26',
    month: 'APR',
    location: 'Main Hall, Church of Christ',
    time: '8:00 AM – 12:00 PM',
    colorClass: 'bg-green-500',
  },
  {
    id: 'ev3',
    title: 'Evangelism Campaign — House to House',
    day: '10',
    month: 'MAY',
    location: 'Various locations, Ekot Ekpene',
    time: '7:00 AM – 1:00 PM',
    colorClass: 'bg-purple-500',
  },
  {
    id: 'ev4',
    title: 'Graduation Service & Thanksgiving',
    day: '25',
    month: 'MAY',
    location: 'Church Auditorium, Ekot Ekpene',
    time: '10:00 AM – 2:00 PM',
    colorClass: 'bg-amber-500',
  },
]

const CONGREGATIONS: Congregation[] = [
  {
    id: 'cg1',
    name: 'Church of Christ, Ekot Ekpene',
    address: '7b Esa Atan, Ekot Ekpene, Akwa Ibom',
    serviceTime: 'Sun 9:00 AM',
    city: 'Ekot Ekpene',
  },
  {
    id: 'cg2',
    name: 'Church of Christ, Uyo Central',
    address: '14 Oron Road, Uyo, Akwa Ibom',
    serviceTime: 'Sun 8:30 AM',
    city: 'Uyo',
  },
  {
    id: 'cg3',
    name: 'Church of Christ, Aba North',
    address: '3 Port Harcourt Road, Aba, Abia State',
    serviceTime: 'Sun 9:00 AM',
    city: 'Aba',
  },
  {
    id: 'cg4',
    name: 'Church of Christ, Calabar',
    address: '22 Murtala Muhammed Highway, Calabar',
    serviceTime: 'Sun 8:00 AM',
    city: 'Calabar',
  },
]

export function usePublicMockData() {
  const teachingsStore = usePublicTeachingsStore()
  const liveStreamStore = usePublicLiveStreamStore()

  function seedPublic() {
    if (teachingsStore.sermons.length === 0) {
      teachingsStore.sermons = SERMONS
    }
    if (teachingsStore.sundaySchool.length === 0) {
      teachingsStore.sundaySchool = LESSONS
    }
    if (liveStreamStore.recordedStreams.length === 0) {
      liveStreamStore.recordedStreams = RECORDED_STREAMS
    }
    if (!liveStreamStore.currentStream) {
      liveStreamStore.currentStream = CURRENT_LIVE_STREAM
    }
  }

  return {
    seedPublic,
    SERMONS,
    LESSONS,
    RECORDED_STREAMS,
    CURRENT_LIVE_STREAM,
    EVENTS,
    CONGREGATIONS,
  }
}
